TelephoneDirectory.MVC/Controllers/PersonsController.cs
using System.Collections;
using FluentValidation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;
using X.PagedList.Mvc;
using TelephoneDirectory.Business.Abstract;
using TelephoneDirectory.Business.BusinessAspects.Autofac;
using TelephoneDirectory.Entities.Concrete;
using TelephoneDirectory.MVC.Filters;
using TelephoneDirectory.MVC.Models;
using TelephoneDirectory.Core.Utilities.Results;
using X.PagedList.Extensions;
using TelephoneDirectory.Business.ValidationRules.FluentValidation;
using TelephoneDirectory.Core.Aspects.AutofacAspect;
using System;


namespace TelephoneDirectory.MVC.Controllers
{
    [Authorize(AuthenticationSchemes = "Login")]
    [Authorize(Roles = "Moderator")]
    public class PersonsController : Controller
    {
        private readonly IPersonService _personService;


        public PersonsController(IPersonService personService)
        {
            _personService = personService;

        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        [AllowAnonymous]
        public IActionResult Index(string firstName, string lastName, string phoneNumber, int page = 1, int pageSize = 10)
        {
            IEnumerable<Person> persons = _personService.GetAll();


            if (!string.IsNullOrEmpty(firstName))
            {
                persons = persons.Where(p => p.Name.Contains(firstName, StringComparison.OrdinalIgnoreCase));
            }


            if (!string.IsNullOrEmpty(lastName))
            {
                persons = persons.Where(p => p.SurName.Contains(lastName, StringComparison.OrdinalIgnoreCase));
            }


            if (!string.IsNullOrEmpty(phoneNumber))
            {
                persons = persons.Where(p => p.PhoneNumber.Contains(phoneNumber));
            }


            var personList = persons.Select(p => new PersonListViewModel
            {
                Id = p.Id,
                Name = p.Name,
                SurName = p.SurName,
                PhoneNumber = p.PhoneNumber
            });


            var pagedPersons = personList.ToPagedList(page, pageSize);

            return View(pagedPersons);
        }


        public IActionResult Add()
        {

            return View();

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(Person person)
        {
            try
            {
                _personService.Add(person);
                return RedirectToAction("Index");
            }
            catch (ValidationException ex)
            {
                foreach (var error in ex.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.ErrorMessage);
                }
            }

            return View(person);
        }


        public IActionResult Update(int id)
        {
            var result = _personService.FindById(id);
            if (result.Success && result.Data != null && result.Data.Count > 0)
            {
                var viewModel = new PersonListViewModel
                {
                    Persons = result.Data
                };
                return View(viewModel);
            }
            else
            {
                // Hata durumunu veya yönlendirmeyi kontrol edin
                return RedirectToAction("Index"); // Alternatif olarak bir hata sayfasına yönlendirin
            }
        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual IActionResult Update(PersonListViewModel updateViewModel)
        {
            try
            {

                if (ModelState.IsValid)
                {
                    // updateViewModel.Persons listesini işleyin
                    foreach (var person in updateViewModel.Persons)
                    {
                        _personService.Update(person);
                    }

                    return RedirectToAction("Index");
                }
            }
            catch (ValidationException ex)
            {
                foreach (var error in ex.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.ErrorMessage);
                }
            }

            return View(updateViewModel);
        }

        public IActionResult Delete(Person person)
        {

            _personService.Delete(person);

            return RedirectToAction("Index");

        }
        public IActionResult Detail(int id)
        {
            var result = _personService.FindById(id);

            // Gelen sonucu doğrudan List<Person> yerine result.Data olarak atar
            if (result.Success)
            {
                var detail = new PersonListViewModel
                {
                    Persons = result.Data // result.Data ifadesi List<Person> döndürür
                };

                return View(detail);
            }
            else
            {
                // Eğer hata varsa hata mesajı gösterilebilir
                return View("Index");
            }
        }
        [AllowAnonymous]
        public IActionResult PageNotFound()
        {
            Response.StatusCode = 404; // Set the status code to 404
            return View();
        }

    }
}

TelephoneDirectory.MVC/Views/Persons/Add.cshtml
@model TelephoneDirectory.Entities.Concrete.Person
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="container">
    <div class="py-5 text-center">
        <h2>Kişi Ekleme</h2>
        <p class="lead">Lütfen bilgileri giriniz</p>

    </div>

    <div class="row">

        <div class="col-md-12 order-md-1">
            <h4 class="mb-3">Bilgiler</h4>
            @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })

            @using (Html.BeginForm("Add", "Persons", FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                <div class="form-group">
                    <label for="Name">@Html.DisplayNameFor(p => p.Name)</label>
                    @Html.TextBoxFor(x => x.Name, new { @class = "form-control", placeholder = "Adınızı giriniz" })

                </div>

                <div class="form-group">
                    <label for="SurName">@Html.DisplayNameFor(p => p.SurName)</label>
                    @Html.TextBoxFor(x => x.SurName, new { @class = "form-control", placeholder = "Soyadınızı giriniz" })

                </div>

                <div class="form-group">
                    <label for="PhoneNumber">@Html.DisplayNameFor(p => p.PhoneNumber)</label>
                    @Html.TextBoxFor(x => x.PhoneNumber, new { @class = "form-control", placeholder = "Telefon numaranızı giriniz" })

                </div>


                <div class="form-group">
                    <input type="submit" value="Kaydet" class="btn btn-success" />
                </div>

            }
        </div>

    </div>

</div>

}

TelephoneDirectory.MVC/Views/Persons/AdminIndex.cshtml
@{
    ViewBag.Title = "AdminIndex";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Admin Index</h2>

TelephoneDirectory.MVC/Views/Persons/Detail.cshtml
@model TelephoneDirectory.MVC.Models.PersonListViewModel
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-lg">
        <div class="ibox">
            @foreach (var person in Model.Persons)
            {
            <div class="ibox-head">
                    <b>@Html.DisplayFor(x => person.Id) nolu Kişi Bilgileri</b>
            </div>
            <div class="ibox-body">
                <div class="form-group">
                    <b>Kişi İsmi:</b>
                        @Html.DisplayFor(x => person.Name)
                </div>
                <div class="form-group">
                    <b>Kişi Soyismi:</b>
                        @Html.DisplayFor(x => person.SurName)
                </div>
                <div class="form-group">
                    <b>Kişi Telefonu:</b>
                        @Html.DisplayFor(x => person.PhoneNumber)
                </div>
                    <div class="form-group">
                    @Html.ActionLink("Kişi Listesi", "Index", new {}, new { @class = "btn btn-info btn-sm" })
                    </div> 
                    </div>
            }
            </div>
    
    </div>
</div>

TelephoneDirectory.MVC/Views/Persons/Index.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Core
@model X.PagedList.IPagedList<TelephoneDirectory.MVC.Models.PersonListViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form action="@Url.Action("Index", "Persons")" method="get" style="margin-bottom: 20px; padding: 15px; border: 1px solid #ddd; border-radius: 5px; max-width: 400px;">
   
    <div style="margin-bottom: 15px;">
        <label for="firstName" style="font-weight: bold;">Ad:</label>
        <input type="text" name="firstName" id="firstName" class="form-control"
               placeholder="Ad giriniz" style="width: 100%; padding: 8px; margin-top: 5px;">
    </div>
   
    <div style="margin-bottom: 15px;">
        <label for="lastName" style="font-weight: bold;">Soyad:</label>
        <input type="text" name="lastName" id="lastName" class="form-control"
               placeholder="Soyad giriniz" style="width: 100%; padding: 8px; margin-top: 5px;">
    </div>
  
    <div style="margin-bottom: 15px;">
        <label for="phoneNumber" style="font-weight: bold;">Telefon Numarası:</label>
        <input type="text" name="phoneNumber" id="phoneNumber" class="form-control"
               placeholder="Telefon numarası giriniz" style="width: 100%; padding: 8px; margin-top: 5px;">
    </div>

    <div>
        <button type="submit" class="btn btn-primary" style="padding: 10px 20px;">Ara</button>
    </div>
</form>


@Html.Partial("_PartialIndex");

TelephoneDirectory.MVC/Views/Persons/PageNotFound.cshtml
<h1>404 - Page Not Found</h1>
<p>The page you are looking for does not exist or you do not have permission to access it.</p>

TelephoneDirectory.MVC/Views/Persons/Update.cshtml
@model TelephoneDirectory.MVC.Models.PersonListViewModel
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <div class="py-5 text-center">
        <h2>Kişi Düzenle</h2>
        <p class="lead">Lütfen bilgileri düzenleyiniz</p>
    </div>

    <div class="row">
        <div class="col-md-12 order-md-1">
            <h4 class="mb-3">Bilgiler</h4>

            @using (Html.BeginForm("Update", "Persons", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })

                @if (Model?.Persons != null && Model.Persons.Count > 0)
                {
                    @for (int i = 0; i < Model.Persons.Count; i++)
                    {
                        <div>
                            @Html.HiddenFor(m => m.Persons[i].Id)
                            <div class="form-group">
                                @Html.LabelFor(m => m.Persons[i].Name, "Ad")
                                @Html.TextBoxFor(m => m.Persons[i].Name, new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.Persons[i].SurName, "Soyad")
                                @Html.TextBoxFor(m => m.Persons[i].SurName, new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.Persons[i].PhoneNumber, "Telefon Numarası")
                                @Html.TextBoxFor(m => m.Persons[i].PhoneNumber, new { @class = "form-control" })
                            </div>
                        </div>
                    }
                }
                else
                {
                    <p>Kişi bulunamadı.</p>
                }
                <button class="btn btn-primary btn-lg btn-block" type="submit">Güncelle</button>
                <a href="@Url.Action("Index", "Persons")" class="btn btn-secondary btn-sm btn-block">Vazgeç</a>

            }
        </div>
    </div>
</div>

TelephoneDirectory.MVC/Views/Persons/_PartialIndex.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Core
@model X.PagedList.IPagedList<TelephoneDirectory.MVC.Models.PersonListViewModel>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Yönetici Girişi</title>
    <style>
        body {
            margin: 0;
            padding: 0;
        }

        .admin-button {
            position: fixed; /* Sabitler */
            top: 75px; /* Sayfanın üstünden 10px */
            right: 10px; /* Sayfanın sağından 10px */
            z-index: 9999; /* Diğer elementlerin üstünde */
            background-color: #6c757d;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            text-decoration: none;
            font-size: 14px;
            cursor: pointer;
        }


        .admin-button:hover {
            background-color: #5a6268; /* Hover efekti */
        }
    </style>
</head>
<body>
<div class="row">
    <div class="col-lg">
        <div class="ibox">
            <div class="ibox-head">
                Kişi Listesi
            </div>
            <div class="ibox-body">
                <table class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <td>İsim</td>
                        <td>Soyisim</td>
                        <td>Telefon Numarası</td>
                        @if (User.IsInRole("Moderator"))
                        {
                            <td>Düzenle</td>
                            <td>Bilgi</td>
                            <td>Silme</td>
                        }
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var person in Model)
                    {
                        <tr>
                            <th>@Html.DisplayFor(x => person.Id)</th>
                            <td>@Html.DisplayFor(x => person.Name)</td>
                            <td>@Html.DisplayFor(x => person.SurName)</td>
                            <td>@Html.DisplayFor(x => person.PhoneNumber)</td>
                            @if (User.IsInRole("Moderator"))
                            {
                                <td>
                                    @Html.ActionLink("Düzenle", "Update", new { id = person.Id }, new { @class = "btn btn-warning  btn-sm" })
                                </td>
                                <td>
                                    @Html.ActionLink("Bilgi", "Detail", new { id = person.Id }, new { @class = "btn btn-info btn-sm" })
                                </td>
                                <td style="margin-bottom: 5px;">
                                    <button class="btn btn-danger btn-sm" style="display: block; width: 25%;"
                                            onclick="confirmDeletion('@person.Id', '@person.Name')">
                                        Sil
                                    </button>
                                </td>
                            }
                        </tr>
                    }
                    <!-- Yönetici Girişi Butonu -->
                    @if (User.Identity.IsAuthenticated == false)
                    {
                        <a href="/Users/Login" class="admin-button">Yönetici Girişi</a>
                    }
                    </tbody>
                </table>

                @Html.PagedListPager(Model, page => Url.Action("Index", "Persons", new { page }), new PagedListRenderOptions
                {
                    UlElementClasses = new[] { "pagination" },
                    LiElementClasses = new[] { "page-item" },
                    PageClasses = new[] { "page-link" }
                })
                @if (User.IsInRole("Moderator"))
                {
                    <div class="form-group">
                        @Html.ActionLink("Yeni Kişi Ekle", "Add", new { }, new { @class = "btn btn-success btn-sm" })
                    </div>
                }
                else
                {
                    <div style="display: none;">
                        @Html.ActionLink("Yeni Kişi Ekle", "Add", new { }, new { @class = "btn btn-success btn-sm" })
                    </div>
                }


                
            </div>
        </div>
    </div>
</div>
</body>
</html>